name: FlutterMasters

workflows:
  flutter_masters:
    environment:
     groups:
       - "FLUTTER_MASTERS"
     flutter: stable
     java: 11
     ios_signing:
      certificates:
        - FlutterMasterDevelopCertificate
      provisioning_profiles:
        - FlutterMasterProvisionProfile


    triggering:
     events:
        - "push"
     branch_patterns:
       - include: true
         source: true
         pattern: github_actions
    
    scripts:
      - name: KEYCHAIN INIT
        script: keychain initialize

      - name: ADD CERTS
        script: keychain add-certificates

      - name: USE PROFILES
        script: xcode-project use-profiles

      - name: ENV
        script: mkdir env

      - name: CREATE ENV
        script: echo '{"FB_TOKEN":"$FIREBASE_TOKEN"}' > env/dev.json

      - name: SHOW CONTENT
        script: less env/dev.json
        working_directory: env

      - name: BUILD APK
        script: flutter build apk --release

      - name: BUILD IPA
        script: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist

    artifacts:
      -  build/ios/ipa/Apps/clean_architecture.ipa
      -  build/app/outputs/flutter-apk/app-release.apk

    publishing:
     firebase:
      firebase_token: $FIREBASE_TOKEN
      android:
        app_id: $ANDROID_APP_ID
        groups:
          - "testers"
        artifact_type: apk
      ios:
       app_id: $IOS_APP_ID
       groups:
         - "testers"
      
