name: FLUTTER_MASTER
on:
  push:
    branches: [github_actions]

jobs:
  flutter_master_deploy:
    runs-on: macos-latest
    steps:
      #<-------------------INIT CONFIG---------------------->
      - name: COPY .
        uses: actions/checkout@v4

      - name: INSTALL JAVA 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: FIREBASE CONF
        run: npm install -g firebase-tools
      #<----------------  END INIT CONFIG---------------------->

      #<----------------  FLUTTER CONFIG ---------------------->
      - name: FLUTTER INSTALL
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      #<---------------- END FLUTTER CONFIG -------------------->
      #<----------------  CACHE STRATEGY ----------------------->
      - name: CACHE STRATEGY
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            /runner/hostedtoolcache/flutter/
            # **/node_modules

          key: ${{ runner.os }}-flutter-install-cache-${{ hashFiles('**/package_config.json') }}

      # #<---------------- END CACHE STRATEGY ------------------->
      # #<----------------------  GUARDS ------------------------>
      # - name: FLUTTER ANALYZE
      #   run: flutter analyze

      # - name: FLUTTER ANALYZE
      #   run: flutter test
      # #<-------------------- END  GUARDS ---------------------->

      # #<---------------- FLUTTER RELEASES --------------------->

      # - name: GENERATE APK
      #   run: flutter build apk
      # #<---------------- END FLUTTER RELEASES ----------------->
